version: '3.3'
services:
  main:
    build: ./build
    volumes:
      - Temp:/home/
  web:
    build: ./run
    ports:
      - 8082:8080
    depends_on:
      - main
    volumes:
      - Temp:/home/
volumes:
  Temp:
